AddonId: PlayniteModernUIModded
Packages:
  - Version: 2.5.1
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2022-08-20
    PackageUrl: https://github.com/HexSupernatural/PlayniteModernUIModded/releases/download/v2.5.1/PlayniteModernUIModded_2_5_1.pthm
    Changelog:
      - Details View Mod 2.3
      - Vertical View Mod 1.0
  - Version: 2.5.2
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2022-08-20
    PackageUrl: https://github.com/HexSupernatural/PlayniteModernUIModded/releases/download/v2.5.2/PlayniteModernUIModded_2_5_2.pthm
    Changelog:
      - Attempting to Fix DKG Theme Modifier Support & Extra Metadata
      - You can no longer install the theme along side the original Modern UI mod you must pick this one or the original
      - Restore Original constants file it was previously using my custom one
  - Version: 2.6.0
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2022-08-21
    PackageUrl: https://github.com/HexSupernatural/PlayniteModernUIModded/releases/download/v2.6.0/PlayniteModernUIModded_2_6_0.pthm
    Changelog:
      - Platform Info added to Vertical View
      - Genre Info added to Vertical View
      - Series Info added to Vertical View
      - New Mod added Focusable Descriptions in Vertical and Horizontal View this is mainly for controller users so they can now scroll longer descriptions but arrow keys are supported
